### ISSUE TITLE
Setting cgroup in cmdline.txt doesn't need to be done in non-Raspberry Pi nodes

### ISSUE THREAD

**Issue by RickCoxDev** [RickCoxDev/home-cluster#610]
The following step in the k3s-common role doesn't need to be done if the node isn't a Raspberry Pi. A conditional needs to be added to check the node and only execute if the node is a Raspberry Pi.
```
- name: Enable container features
  replace:
    path: /boot/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
  - "cgroup_enable=cpuset"
  - "cgroup_memory=1"
  - "cgroup_enable=memory"
```
