### ISSUE TITLE
Setting a static ip address in dhcpd.conf doesn't work for Ubuntu nodes

### ISSUE THREAD

**Issue by RickCoxDev** [RickCoxDev/home-cluster#611]
The following step in the k3s-common role doesn't find the dhcpd.conf file in Ubuntu nodes. This works for Raspberry Pi nodes. This should only execute if the file exists and an extra step should be added to update the appropriate config file for Ubuntu.
```
- name: Configure static IP in /etc/dhcpcd.conf
  notify: reboot
  lineinfile:
    dest: /etc/dhcpcd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
  - {regexp: "^interface eth[0-9]$", line: "interface {{ connection.interface }}"}
  - {regexp: "^static ip_address", line: "static ip_address={{ connection.ip_address }}"}
  - {regexp: "^static routers", line: "static routers={{ connection.router }}"}
```
